### ISSUE TITLE
OpenResty部署问题

### ISSUE THREAD

**Issue by liangjingdev** [daydreamdev/MeetingFilm#8]
您好，请问使用OpenResty配置FTP图片服务器的时候，有遇到端口报403的错误吗？

**Comment by wangfei910** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        有的，忘记之前咋解决的了，现在重新部署也出现了这个问题
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                wangfei5897305
                            
                    
                        
                            
                                    wangfei5897305@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年3月1日 14:09，梁竞<notifications@github.com> 写道： 


您好，请问使用OpenResty配置FTP图片服务器的时候，有遇到端口报403的错误吗？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liangjingdev** [comment]
我这边解决啦，把openresty的配置文件nginx.conf中的第一行user相关的注释去掉，并将执行用户改为root就可以啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王飞 <notifications@github.com&gt;
发送时间: 2020年3月2日 14:08
收件人: daydreamdev/MeetingFilm <MeetingFilm@noreply.github.com&gt;
抄送: 梁竞 <1184106223@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[daydreamdev/MeetingFilm] OpenResty部署问题 (#8)



 
 
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     
         有的，忘记之前咋解决的了，现在重新部署也出现了这个问题
         
     
         
             
         
     
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 wangfei5897305
                             
                     
                         
                             
                                     wangfei5897305@outlook.com
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     在2020年3月1日 14:09，梁竞<notifications@github.com&gt; 写道： 
 
 
 您好，请问使用OpenResty配置FTP图片服务器的时候，有遇到端口报403的错误吗？
 
 
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wangfei910** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        好的，多谢
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                wangfei5897305
                            
                    
                        
                            
                                    wangfei5897305@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年3月2日 15:25，梁竞<notifications@github.com> 写道： 


我这边解决啦，把openresty的配置文件nginx.conf中的第一行user相关的注释去掉，并将执行用户改为root就可以啦















发自我的iPhone











------------------ 原始邮件 ------------------



发件人: 王飞 <notifications@github.com&gt;



发送时间: 2020年3月2日 14:08



收件人: daydreamdev/MeetingFilm <MeetingFilm@noreply.github.com&gt;



抄送: 梁竞 <1184106223@qq.com&gt;, Author <author@noreply.github.com&gt;



主题: 回复：[daydreamdev/MeetingFilm] OpenResty部署问题 (#8)















 



 



 



 



 



     font{ 



         line-height: 1.6; 



     } 



     ul,ol{ 



         padding-left: 20px; 



         list-style-position: inside; 



     } 



 



 



     



     



         有的，忘记之前咋解决的了，现在重新部署也出现了这个问题



         



     



         



             



         



     



     



      



     



         



                     



             



                 



                     



                             



                                 



                             



                             



                                 wangfei5897305



                             



                     



                         



                             



                                     wangfei5897305@outlook.com



                             



                         



                 



             



         



         



     



     



         签名由



         网易邮箱大师



         定制



     



  



 



     在2020年3月1日 14:09，梁竞<notifications@github.com&gt; 写道： 



 



 



 您好，请问使用OpenResty配置FTP图片服务器的时候，有遇到端口报403的错误吗？



 



 



 



 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 



—



You are receiving this because you authored the thread.



Reply to this email directly, view it on GitHub, or unsubscribe.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
